---
- hosts: perf_test_node
  tasks:
  - shell: |
      #!/bin/bash
      if [ ! -d /home/app/fortio ]; then
        sudo rm -f /usr/bin/fortio || true
        sudo rm -rf /usr/share/fortio || true
        sudo rm -f /home/app/fortio/fortio-linux_x64-1.3.1.tgz || true
        mkdir -p /home/app/fortio || true
        cd /home/app/fortio
        wget https://github.com/fortio/fortio/releases/download/v1.3.1/fortio-linux_x64-1.3.1.tgz
        tar -xf fortio-linux_x64-1.3.1.tgz
        cd /usr/share
        sudo ln -s /home/app/fortio/usr/share/fortio fortio
        cd /usr/bin
        sudo ln -s /home/app/fortio/usr/bin/fortio fortio
      fi
      sudo pkill fortio; nohup /home/app/fortio/usr/bin/fortio server -http-port 8888 -data-dir /home/app/fortio > /home/app/fortio/fortio.log 2>&1 &
      sudo rm -f /home/app/fortio/*.json
      throughput_base=200
      latency99_base=200
      # sleep 10 seconds to wait for mesh to be ready
      sleep 10
      # warm up by 1 minute
      curl -s http://localhost:8888/fortio/\?labels\=MeshPerfTest-Warmup\&qps\=50\&t\=1m\&c\=4\&p\=50%2C+75%2C+90%2C+95%2C+99\&stdclient\=on\&save\=on\&load\=Start\&H\=WM_CONSUMER.ID%3Afeae28cb-f9f7-3c21-beab-ae66c4440fd1\&H\=WM_SVC.NAME%3ASERVICE-MESH-TEST-PROVIDER\&H\=WM_SVC.ENV%3Aqa1\&url\=http%3A%2F%2Flocalhost%3A4141%2Fbasic > /dev/null &
      sleep 70
      # run test by 3 minutes
      curl -s http://localhost:8888/fortio/\?labels\=MeshPerfTest\&qps\=-1\&t\=3m\&c\=4\&p\=50%2C+75%2C+90%2C+95%2C+99\&stdclient\=on\&save\=on\&load\=Start\&H\=WM_CONSUMER.ID%3Afeae28cb-f9f7-3c21-beab-ae66c4440fd1\&H\=WM_SVC.NAME%3ASERVICE-MESH-TEST-PROVIDER\&H\=WM_SVC.ENV%3Aqa1\&url\=http%3A%2F%2Flocalhost%3A4141%2Fbasic > /dev/null &
      sleep 190
      throughput=`grep "ActualQPS" /home/app/fortio/*MeshPerfTest.json |tr -s ' ' |cut -d ' ' -f3 | cut -d '.' -f1`
      latency99=`grep "\"Percentile\": 99" -A1 /home/app/fortio/*MeshPerfTest.json | grep Value | tr -s ' ' |cut -d ' ' -f3 | awk '{printf "%.0f\n",$1*1000}'`
      echo "========= PERF TEST DATA: throughput : $throughput, throughput_base : $throughput_base, latency99 : $latency99, latency99_base : $latency99_base ========="
      if [ $((throughput)) -lt $throughput_base -o $((latency99)) -gt $latency99_base ] ; then
         echo "========= Failure: Performance test results is below threshold: throughput_base=[$throughput_base] latency99_base=[$latency99_base]"
         exit -1
      fi
      sudo pkill fortio
    register: output
  - debug: msg="{{ output.stdout }}"
  - debug: msg="{{ output.stderr }}"
